export const admMenuItems = {
    'MASTER_ENTRY': 1,
    'ME_BANK_IFSC_CODE': 2,
    'ME_GEO_LOCATION': 3,
    'ME_LOCALE_CONFIG': 4,

    'ENTITY_CONFIGURATION': 5,
    'EC_ENTITY_MANAGEMENT': 6,
    'EC_PARENT_ORGANIZATION': 7,
    'EC_REGISTRATION_TYPE': 8,
    'EC_AREA_OF_EXPERTIES': 9,
    'EC_ENTITY_DOCUMENTS': 10,
    'EC_CSR_POLICY_DOCS': 11,
    'EC_USER_DESIGNATION': 12,
    'EC_USER_DOCUMENTS': 13,
    'EC_MANAGE_SERVICES': 14,

    'ACCREDITATION_CONFIG': 15,
    'AC_ACCRED_DOCUMENT': 16,
    'AC_ACCRED_QUESTIONNAIRE': 17,

    'PROJECTS_CONFIGURATION': 18,
    'PC_RFP_DOCUMENTS': 19,
    'CHARGES_SETTING': 29,

    'MANAGE_TEMPLATE': 20,
    'MT_SMS_TEMPLATE': 21,
    'MT_EMAIL_TEMPLATE': 22,

    'CONTENT_MANAGEMENT': 23,
    'CM_TERMS_CONDITION': 24,

    'ADMIN_USER_MANAGEMENT': 25,
    'AUM_VIEW_USER_LIST': 26,
    'AUM_ADD_NEW_USER': 27,
    'ANU_MANAGE_ROLES': 28,

    'MANAGE_REGISTRATION':30,
    'CORPORATES':31,
    'FOUNDATION':32,
    'PHILANTHROPIST':33,
    'IMPLEMENTING_AGENCY':34,
    'ACCREDITION_AGENCY':35,
    'VENDOR':36,
    'CONSULTANT':37,

    'ENTITY_EDIT_PROFILE_REQ': 38,

    'PROJECT_MONITORING':39,
    'PROJECT_FLOATED':40,
    'PROJECT_AWARDED':41,
};