const apiStatus = {
    'RELOAD_PAGE': 1,
    'RESET_LINK_EXPIRED': 2,
    'SESSION_EXPIRED': 3,
    'BACK_TO_PREV_PAGE': 4,
    'MOBILE_EMAIL_VALIDATED': 5,
    'COMPANY_PAN_VALIDATED': 6,
    'GSTIN_NO_VALIDATED': 7,
    'CIN_NO_VALIDATED': 8,
    'PAN_VALIDATED': 9,
    'IFSC_CODE_VALIDATED': 10,
    'BANK_ACCOUNT_VALIDATED': 11,
    'REG_SUCCESS_NO_PAYMENT': 12,
    'REG_PAYMENT_REQUIRED': 13,
    'ACCOUNT_NOT_ACTIVATED': 14,
    'REMOVE_RESUME_REGISTER': 15,
    'NO_PERMISSION': 16,
};

module.exports = { apiStatus };