const entityMenuItems = {
    'PROJECT_MANAGEMENT': 1,
    'PM_CREATE_PROJECT': 11,
    'PM_IA_SELECTION': 12,
    'PM_CROWD_FUNDING': 28,
    'PM_FUND_TRANSFER': 13,
    'PM_PROJECT_MONITORING': 14,

    'PROJECT_DISCOVERY': 2,
    'PD_DISCOVERY': 19,
    'PD_STATUS': 20,
    'PD_HISTORY': 21,
    'PD_MONITORING': 29,

    'INITIATE_ACCREDITION': 24,
    'INIT_ACCRED_REQUEST': 25,
    'INIT_ACCRED_STATUS': 26,

    'APPROVALS': 8,
    'APPROV_NGO_ACCREEDITION': 27,

    'ENTITY_DISCOVERY': 22,
    'ED_CORPORATE_SEARCH': 5,
    'ED_FOUNDATION_SEARCH': 23,
    'ED_IA_SEARCH': 3,
    'ED_AA_SEARCH': 7,
    'ED_VENDOR_SEARCH': 4,
    'ED_CONSULTANT_SEARCH': 6,
    'ED_PHILANTHROPIST_SEARCH': 11000,

    'RFP_PROPOSAL': null,

    'USER_MANAGEMENT': 10,
    'UM_ROLE_CREATION': 15,
    'UM_USER_CREATION': 16,
    'UM_ROLE_APPROVAL': 17,
    'UM_USER_APPROVAL': 18,
};

module.exports = {
    entityMenuItems
};