# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gms-backend
  template:
    metadata:
      labels:
        app: gms-backend
    spec:
      containers:
      - name: gms-backend
        image: gcr.io/ranjeet/gms-backend:latest
        ports:
        - containerPort: 3000
