# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gms-backend
spec:
  selector:
    app: gms-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
